<a href="https://colab.research.google.com/github/stlmh/machine_learning/blob/main/%D0%A1%D1%82%D0%B5%D0%BB%D1%8C%D0%BC%D0%B0%D1%85_%D0%9F%D0%A0_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **ПР_1_МН**
08.09.2025

In [ ]:
import numpy as np
np.__version__

'2.0.2'

1. Створи матрицю 3*3, заповни її цілими випадковими числами від 1 до 5

In [ ]:
matrix = np.random.randint(1, 6, size=(3, 3))
matrix

array([[4, 2, 2],
       [1, 3, 5],
       [4, 1, 2]])

2. Обчислити визначник матриці

In [ ]:
det = np.linalg.det(matrix)
det

np.float64(18.000000000000004)

3. Знайти добуток всіх елементів матриці

In [ ]:
product = np.prod(matrix)
product

np.int64(1920)

In [ ]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(1920)

4. Знайти суму всіх елементів матриці

In [ ]:
sum = np.sum(matrix)
sum

np.int64(24)

5. Обчислити найбільший, найменший елементи

In [ ]:
max_element = np.max(matrix)
print("Найбільший елемент матриці:", max_element)

min_element = np.min(matrix)
print("Найменший елемент матриці:", min_element)

Найбільший елемент матриці: 5
Найменший елемент матриці: 1


6. Знайти середнє значення елементів матриці

In [ ]:
mean = np.mean(matrix)
print("Середнє значення елементів матриці:", mean)

Середнє значення елементів матриці: 2.6666666666666665


7. Знайти матрицю, що складена з квадратних коренів.

In [ ]:
sqrt_matrix = np.sqrt(matrix)

print("Матриця квадратних коренів:")
print(sqrt_matrix)

Матриця квадратних коренів:
[[2.         1.41421356 1.41421356]
 [1.         1.73205081 2.23606798]
 [2.         1.         1.41421356]]


8. Обчислити суму елементів кожного рядка. Відповідь записати як вектор-стовпчик

In [ ]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)

print("Сума елементів кожного рядка:")
print(row_sums)

Сума елементів кожного рядка:
[[8]
 [9]
 [7]]


9. Створити вектор, що містить 25 елементів. Заповнити числами від 0 до 9. Відсортувати числа за спаданням.

In [ ]:
vector = np.random.randint(0, 10, size=25)

print("Початковий вектор:")
print(vector)

# Сортуємо числа за спаданням
sorted_vector = np.sort(vector)[::-1]

print("Вектор після сортування за спаданням:")
print(sorted_vector)

Початковий вектор:
[8 3 1 2 7 1 3 8 3 5 4 7 4 5 8 8 9 9 9 3 7 6 4 2 8]
Вектор після сортування за спаданням:
[9 9 9 8 8 8 8 8 7 7 7 6 5 5 4 4 4 3 3 3 3 2 2 1 1]


10. Знайти моду, медіану, середнє, максимальне, мінімальне значення

In [ ]:
from scipy import stats

# Мода
mode = stats.mode(vector)

# Медіана
median = np.median(vector)

# Середнє
mean = np.mean(vector)

# Максимальне
max_value = np.max(vector)

# Мінімальне
min_value = np.min(vector)

print("Мода:", mode)
print("Медіана:", median)
print("Середнє:", mean)
print("Максимальне значення:", max_value)
print("Мінімальне значення:", min_value)

Мода: ModeResult(mode=np.int64(8), count=np.int64(5))
Медіана: 5.0
Середнє: 5.36
Максимальне значення: 9
Мінімальне значення: 1


11. Створити дві матриці числами від 1 до 10. Обчислити суму, різницю, поелементний добуток, частку

In [ ]:
# Створюємо дві матриці 4x4 із випадкових цілих чисел від 1 до 10
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)

Матриця 1:
[[ 5  4  8  7]
 [ 2  4  9  7]
 [10  6  6  3]
 [10  2  6  4]]

Матриця 2:
[[10  7 10  1]
 [ 4  2  9  8]
 [ 5  5  9  5]
 [ 2  8  7  6]]


In [22]:
#Сума
matrix_sum = matrix1 + matrix2

#Різниця
matrix_diff = matrix1 - matrix2

#Добуток
matrix_product = matrix1 * matrix2

#Частка
matrix_division = np.divide(matrix1, matrix2, where=(matrix2!=0))

print("\nСума матриць:")
print(matrix_sum)

print("\nРізниця матриць:")
print(matrix_diff)

print("\nПоелементний добуток матриць:")
print(matrix_product)


Сума матриць:
[[15 11 18  8]
 [ 6  6 18 15]
 [15 11 15  8]
 [12 10 13 10]]

Різниця матриць:
[[-5 -3 -2  6]
 [-2  2  0 -1]
 [ 5  1 -3 -2]
 [ 8 -6 -1 -2]]

Поелементний добуток матриць:
[[50 28 80  7]
 [ 8  8 81 56]
 [50 30 54 15]
 [20 16 42 24]]


12. Задати вектор-рядок, що містить дійсні числа 1.0-8.0. Зробити матрицю 3*3. Помножити на вектор-рядок, що містить числа 0.0-2.0

In [27]:
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [28]:
x1 = x.reshape((3, 3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [29]:
x2 = np.arange(3.0)
x2

array([0., 1., 2.])

In [30]:
np.multiply(x1,x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])