<a href="https://colab.research.google.com/github/stlmh/machine_learning/blob/main/%D0%A1%D1%82%D0%B5%D0%BB%D1%8C%D0%BC%D0%B0%D1%85_%D0%9F%D0%A0_1_%D1%87%D0%B0%D1%81%D1%82%D0%B8%D0%BD%D0%B02_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**Завдання 1**
Задати вектор, що складається з перших п'яти натуральних чисел.

In [2]:
vector = np.array([1, 2, 3, 4, 5])
print(vector)

[1 2 3 4 5]


**Завдання 2**
Транспонувати вектор.

In [6]:
v1 = np.matrix([1, 2, 3, 4, 5])
print(v1)

v2 = v1.T
v2

[[1 2 3 4 5]]


matrix([[1],
        [2],
        [3],
        [4],
        [5]])

**Завдання 3**
Напишіть функцію, яка перевертає вектор у зворотному порядку

In [7]:
v = np.array([1, 2, 3, 4, 5])
print(v[::-1])

[5 4 3 2 1]


**Завдання 4** Обчислити середнє значення вектора

In [8]:
print(np.mean(v))

3.0


**Завдання 5** Знайти найбільший і найменший елементи вектора

In [9]:
print(np.max(v))
print(np.min(v))

5
1


**Завдання 6** Обчислити скалярний добуток (dot product) двох векторів

In [14]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(np.dot(v1, v2))
print(v1*v2)

32
[ 4 10 18]


**Завдання 7** Написати функцію, яка нормалізує вектор

In [12]:
from numpy import linalg as LA

In [15]:
v = np.array([1, 2, 3, 4, 5])
norm = np.linalg.norm(v)

print(norm)

v / norm

7.416198487095663


array([0.13483997, 0.26967994, 0.40451992, 0.53935989, 0.67419986])

**Завдання 8** Перевірка ортогональності векторів

In [16]:
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])

np.dot(v1, v2)

np.int64(0)

**Завдання 9** Визначити унікальні елементи вектора

In [17]:
v = np.array([1, 2, 3, 2, 4, 5, 3])
np.unique(v)

array([1, 2, 3, 4, 5])

**Завдання 10** Знайти вектор , що є різницею між двома векторами

In [18]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(v1 - v2)
print(v2 - v1)
print(v1 + v2)
print(v2 + v1)
print(v1 * v2)
print(v2 * v1)
print(v1 / v2)
print(v2 / v1)

[-3 -3 -3]
[3 3 3]
[5 7 9]
[5 7 9]
[ 4 10 18]
[ 4 10 18]
[0.25 0.4  0.5 ]
[4.  2.5 2. ]


**Завдання 11** Перевірити, чи дорівнює довжина вектора 5

In [20]:
vector = np.array([1, 2, 3, 4, 5])
length = np.linalg.norm(vector)

np.isclose(length, 5)

np.False_

**Завдання 12** Задати матрицю, заповнену випадковими числами

In [27]:
a = np.random.randint(0, 11, (3, 3))
a

array([[7, 3, 5],
       [5, 6, 3],
       [2, 9, 7]])

**Завдання 13** Обчислення визначиник матриці

In [28]:
np.linalg.det(a)

np.float64(183.00000000000009)

**Завдання 14** Знаходження оберненої матриці

In [29]:
np.linalg.inv(a)

array([[ 0.08196721,  0.13114754, -0.1147541 ],
       [-0.15846995,  0.21311475,  0.02185792],
       [ 0.18032787, -0.31147541,  0.14754098]])

**Завдання 15** Розв'язати систему лінійних рівнянь

In [30]:
a = np.array([[1, 3, -4], [0, 2, -3], [-2, 2, 5]])
b = np.array([5, 3, 4])

x = np.linalg.solve(a, b)
print(x)

inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print(x1)

[0.38888889 1.83333333 0.22222222]
[0.38888889 1.83333333 0.22222222]


**Завдання 16** Множення двох матриць

In [31]:
a = np.array([[1, 3, -4], [0, 2, -3], [-2, 2, 5]])
b = np.array([5, 3, 4])

np.dot(a, b)

array([-2, -6, 16])

In [32]:
a = np.matrix([[1, 3, -4], [0, 2, -3]])
b = np.matrix([[5, 3, 4], [2, 3, 5], [3, 2, 3]])
print(a)
print(b)
print(np.dot(a, b))

[[ 1  3 -4]
 [ 0  2 -3]]
[[5 3 4]
 [2 3 5]
 [3 2 3]]
[[-1  4  7]
 [-5  0  1]]


**Завдання 17** Транспонування матриць

In [33]:
print(a.T)
print(b.T)

[[ 1  0]
 [ 3  2]
 [-4 -3]]
[[5 2 3]
 [3 3 2]
 [4 5 3]]


In [34]:
print(np.transpose(a))
print(np.transpose(b))

[[ 1  0]
 [ 3  2]
 [-4 -3]]
[[5 2 3]
 [3 3 2]
 [4 5 3]]


**Завдання 18** Перевірка симетричності матриці

In [35]:
matrix = np.matrix([[2, 2, 2],[2, 2, 2],[2, 2, 2]])

np.allclose(matrix, matrix.T)

True

**Завдання 19** Обчислення сліду матриці

In [36]:
np.trace(matrix)

np.int64(6)

**Завдання 20** Сума матриць

In [37]:
a = np.matrix([[1, 2], [3, 4]])
b = np.matrix([[5, 6], [7, 8]])

print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


**Завдання 21** Піднесення матриці до степеня

In [38]:
a = np.matrix([[1, 2], [3, 4]])

np.linalg.matrix_power(a, 2)

matrix([[ 7, 10],
        [15, 22]])

**Завдання 22** Сортування рядків або стовпців матриці

In [39]:
b = np.matrix([[5, 3, 4], [2, 3, 5], [3, 2, 3]])

print(b)
print(np.sort(b, axis=0))
print(np.sort(b, axis=1))
print(np.sort(b, axis=None))

[[5 3 4]
 [2 3 5]
 [3 2 3]]
[[2 2 3]
 [3 3 4]
 [5 3 5]]
[[3 4 5]
 [2 3 5]
 [2 3 3]]
[[2 2 3 3 3 3 4 5 5]]


In [43]:
a = np.array([[1,4],[3,1]])

print(a)
print(np.sort(a))

[[1 4]
 [3 1]]
[[1 4]
 [1 3]]


In [44]:
print(np.sort(a, axis=0))
print(np.sort(a, axis=1))

[[1 1]
 [3 4]]
[[1 4]
 [1 3]]


**Завдання 23** Підрахуй суму елементів кожного рядка матриці. Відповідь запиши, як вектор-стовпчик.

In [45]:
row_sums = np.sum(a, axis=1).reshape(-1, 1)

print("Сума елементів кожного рядка:")
print(row_sums)

Сума елементів кожного рядка:
[[5]
 [4]]
